/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileUsernameImport } from './routes/profile/$username'
import { Route as QuizzesQuizIdIndexImport } from './routes/quizzes/$quizId/index'
import { Route as QuizzesQuizIdFlashcardsImport } from './routes/quizzes/$quizId/flashcards'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileUsernameRoute = ProfileUsernameImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRoute,
} as any)

const QuizzesQuizIdIndexRoute = QuizzesQuizIdIndexImport.update({
  id: '/quizzes/$quizId/',
  path: '/quizzes/$quizId/',
  getParentRoute: () => rootRoute,
} as any)

const QuizzesQuizIdFlashcardsRoute = QuizzesQuizIdFlashcardsImport.update({
  id: '/quizzes/$quizId/flashcards',
  path: '/quizzes/$quizId/flashcards',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameImport
      parentRoute: typeof rootRoute
    }
    '/quizzes/$quizId/flashcards': {
      id: '/quizzes/$quizId/flashcards'
      path: '/quizzes/$quizId/flashcards'
      fullPath: '/quizzes/$quizId/flashcards'
      preLoaderRoute: typeof QuizzesQuizIdFlashcardsImport
      parentRoute: typeof rootRoute
    }
    '/quizzes/$quizId/': {
      id: '/quizzes/$quizId/'
      path: '/quizzes/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof QuizzesQuizIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/quizzes/$quizId/flashcards': typeof QuizzesQuizIdFlashcardsRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/quizzes/$quizId/flashcards': typeof QuizzesQuizIdFlashcardsRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/quizzes/$quizId/flashcards': typeof QuizzesQuizIdFlashcardsRoute
  '/quizzes/$quizId/': typeof QuizzesQuizIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile/$username'
    | '/quizzes/$quizId/flashcards'
    | '/quizzes/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile/$username'
    | '/quizzes/$quizId/flashcards'
    | '/quizzes/$quizId'
  id:
    | '__root__'
    | '/'
    | '/profile/$username'
    | '/quizzes/$quizId/flashcards'
    | '/quizzes/$quizId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  QuizzesQuizIdFlashcardsRoute: typeof QuizzesQuizIdFlashcardsRoute
  QuizzesQuizIdIndexRoute: typeof QuizzesQuizIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  QuizzesQuizIdFlashcardsRoute: QuizzesQuizIdFlashcardsRoute,
  QuizzesQuizIdIndexRoute: QuizzesQuizIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/profile/$username",
        "/quizzes/$quizId/flashcards",
        "/quizzes/$quizId/"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/profile/$username": {
      "filePath": "profile/$username.tsx"
    },
    "/quizzes/$quizId/flashcards": {
      "filePath": "quizzes/$quizId/flashcards.tsx"
    },
    "/quizzes/$quizId/": {
      "filePath": "quizzes/$quizId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
